### ISSUE TITLE
Windows Installation Using Cygwin Is Not Working

### ISSUE THREAD

**Issue by jdcargile** [amix/vimrc#298]
I am getting the following errors when I try to run the setup from Cygwin on Windows 10. Any suggestions?

![image](https://cloud.githubusercontent.com/assets/9474625/23905785/c4ed81f8-0891-11e7-808d-0299061de6ae.png)

**Comment by mastacontrola** [comment]
Have you tried manually typing the command rather than copy paste?

Windows vs. Linux new lines are different.

Windows, often, uses a new line tag of: `\r\n` Where linux (what cygwin is parsing through as well) uses `\n`

I'm only guessing you copy/pasted based on the fact your commands have the trailing \r.

**Comment by amix** [comment]
Don't have access to a Windows box anymore. Hope you resolved this issue and could do a PR with the fix.
