### ISSUE TITLE
foldenable is enabled in js files

### ISSUE THREAD

**Issue by erfanio** [amix/vimrc#304]
For some reason folding is enabled in js files, but other types like json are disabled.
I have `set nofoldenable` in `my _configs.vim`
When I `echo &foldenable` in a `*.js` file I get a 1, but when I do it in a `*.json` file I get a 0.
This happens even after i have reverted all my changes to the config, and only have `set nofoldenable` and no external plugins.
I was wondering if you can guess where this could be coming from, this is a very weird issue.

**Comment by heroandtn3** [comment]
I have the same problem, any idea to solve it?

**Comment by fedekau** [comment]
Same here! I did a fresh install, saw the problem and tried to solve it with `set nofoldenable` but it does not work 🤔

**Comment by erfanio** [comment]
look at `vimrcs/filetypes.vim:29`  
```
au FileType javascript setl fen
```  
This enables fold for javascript files only and disregards your vimrc

**Comment by amix** [comment]
You can add your own configs by following this:
https://github.com/amix/vimrc#how-to-include-your-own-stuff

**Comment by ctrlcctrlv** [comment]
It happens because `:au` calls happen _after_ `.vimrc` is loaded. So there's no way to disable this with the `source`d file `~/.vim_runtime/my_configs.vim`, @amix's file is completely false.

So it seems like the only thing you can do is edit the script, making it hard to upgrade, as @erfanio wrote.

However, I thought of another way.

```
[fred@pc 5ch]$ cat ~/.vim_runtime/my_configs.vim
autocmd! FileType
```

How this works is it removes all the `au` commands, so they'll never trigger on the `FileType` event. This disables a lot of stuff, not just the fold. But that doesn't matter to me. If it matters to you, @erfanio's way is the only way for now until @amix actually makes this configurable.

**Comment by artburkart** [comment]
For what it's worth, I'm sure amix was communicating that one could disable the JavaScript-specific folding by adding the following to their `my_configs.vim`:

```vim
au FileType javascript setl nofen
```
