### ISSUE TITLE
[Feature Request] Add Plugins to List

### ISSUE THREAD

**Issue by GaryFurash** [amix/vimrc#383]
Rather than git cloning extra plugins, allow users to list their custom plugins in my_config.vim, and then have Amix install or update them!

**Comment by alphaCTzo7G** [comment]
One of the problems with this approach is that in the `vim` eco-system different plugins use different shortcut keys. As a result, if you just update or add random plugins, like using Vundle, without somebody testing them out, some of the shortcut keys will overlap and conflict, and will create a messy experience.

We can easily do this if we move to `VimPlug` or `Vundle`, but the risk is that if the user uses the latest version of plugins, they might conflict with another plugin (if the plugin has been recently updated and not tested against other plugins). Having a controlled set of plugins (even though they maynot be the latest version), and tested by amix, provides for a better user experience for new users.

I would think that the minor improvements that happen in most VIM plugins are not of concern for most users, and the slow testing and upgrading that amix does, when he finds better plugins, is best for most new users. The VIM plugin echo-system suffers from too many choices, and the paradox of choice. This VIMRC and his approach does a great job in balancing the most useful plugins for the new user, so that they can be productive on the first day of using VIM, without having to worry about which fancy new plugin to chose from.

Experienced users can always upgrade or add plugins by themselves.

**Comment by amix** [comment]
What @alphaCTzo7G said :)
