### ISSUE TITLE
How to go to the beginning of line?

### ISSUE THREAD

**Issue by ryanzzff** [amix/vimrc#389]
`0` didn't go to the beginning of line as expected,
now it have the same behaviour as `^`, which moves the cursor to the beginning of first non-blank character of the line

**Comment by alphaCTzo7G** [comment]
Yeah.. I have noticed this too.

Seems to be happening because of the `basic.vim` file in ~/.vim_runtime/vimrcs. However, I havent figured out which line is causing this.

I dont often need to go to the 0th character.. but if I do, I just use `h` to navigate to that character.

**Comment by ryanzzff** [comment]
I found the line cause this, but I just don't understand why this mapping is needed.

`basic.vim` line 287:
```
" Remap VIM 0 to first non-blank character
map 0 ^
```

**Comment by alphaCTzo7G** [comment]
Oh ok.. thanks for pointing that out.

@amix , is there a reason to map 0 to ^? Wondering how it helps you?

**Comment by amix** [comment]
@alphaCTzo7G It's just not very often I need to go at the actual beginning, I find it much more useful to go to the first non-whitespace char.

**Comment by jetzerb** [comment]
I just ran into this same issue, and figured that even though the issue was closed long ago, I'd offer some workarounds for anyone who stumbles upon this issue in the future:

### Go With The Flow
If you want to embrace @amix's preferences, you can use [other means to get to the beginning of the line](https://stackoverflow.com/a/39822689/12859753) while in command mode:
- `|` or `1|`: by itself, `|` will take you to the beginning of the line.  More generically, you can enter a number first to go to a specific column (_e.g._ `17|` goes to the 17th column).  Note that "columns" are computed using your specified tab width.  So if you `set ts=8`, then `1|` - `8|` will take you to the tab character at the beginning of the line.
- `g0`: go to the beginning of the physical line on the terminal (differs from `|` only when lines are wrapped)

### Revert To Standard Behavior
If you want the original behavior where
- `0` takes you to the beginning of the line
- `^` takes you to the first non-blank character on the line

then update `~/.config/nvim/my_configs.vim` to undo the mapping:
```vim
" restore standard behavior for moving to beginning of line via '0'
unmap 0
```
