### ISSUE TITLE
The Vim is LAG !!

### ISSUE THREAD

**Issue by HusterYP** [amix/vimrc#427]
When I use this config for my vim for C/C++ project, I find that the vim is lag, how to fix it ?? 
I am using the ArchLinux.

**Comment by Paraidomat** [comment]
Hi,

Is your C/C++ project using very long files?
What i found is, that vim tends to get slow if the files get long due to the autocompletion.

**Comment by HusterYP** [comment]
No !  Sometimes it just has 100 -- 200 lines ! I googled that , and I found that it is caused by the file fold of vim;
Maybe you can found the answer below : 
https://github.com/python-mode/python-mode/issues/523

**Comment by Paraidomat** [comment]
Ahhh yeah right! I knew it had to do something with long files. But folding definitely rings a bell for me, too.

Okay, what you could do of course is deactivate folding?

**Comment by HusterYP** [comment]
Well, We don't need to be so extreme , I just `set foldmethod=indent`  !!

**Comment by alphaCTzo7G** [comment]
`Python-mode` is typically for python(`.py`) files.. if its `c/c++` files it shouldn't be affected too much.

I solved it by using a plugin called `FastFold`.. It pretty much solved the folding problem for me: https://github.com/python-mode/python-mode/issues/523#issuecomment-362868426

If I remember correctly, this happens because everytime you try to change the file.. VIM will try to calculate the indents in `insertmode`. The `FastFold` plugin basically `Speed up Vim by updating folds only when called-for.`

For me `python-mode` along with this plugin is working pretty well.

**Comment by amix** [comment]
Thanks, @alphaCTzo7G 

YOu might also want to try to disable Ale, which is the syntax checker/linter:
https://github.com/dense-analysis/ale#faq-disable-linters
