### ISSUE TITLE
Rookie question  - Can't remove the highlights after search 

### ISSUE THREAD

**Issue by ashutoshmjain** [amix/vimrc#501]
@amix ... first , thanks for this great resource. You woudn't know how much this has configuration helped me enjoy writing in vim.  

Please take a look at row 211. Does it mean that I just press leader  (,)to remove the highlights ? I tried but it doesn't work . No big deal though as Ican always use :noh but just wanted to share the feedback or may be I am doing something wrong  .. 

Please keep up the good work 

Thanks

**Comment by joe-el-khoury** [comment]
`<cr>` stands for "carriage-return", which is the enter key on your keyboard.

The command to unhighlight searched text is `<leader><cr>`, which translates to `<leader><enter>`.

**Comment by viktor196** [comment]
*E211*
  File "{filename}" no longer available

The file which you have started editing has disappeared, or is no longer
accessible.  Make sure you write the buffer somewhere to avoid losing
changes.  This message is not given when 'buftype' is not empty.


С уважением,Виктор./+7920 6899105

 
 

Sent: Monday, April 08, 2019 at 3:42 AM

**Comment by viktor196** [comment]
Updates can be accomplished by performing a pull with Git inside the plugin directory. For example, to update vim-airline, you would cd into the vim-airline directory inside bundle and pull.

$ cd ~/.vim/bundle/(myp-n)
$ git pull origin master


The same will be true of very plugin that you cloned with Git. You can easily write up a shell script to iterate through each directory and pull and even set it to a cron job to fully automate the update process, if you want to. 

Keep in mind that you can keep Pathogen itself up-to-date the same way because you cloned it from Github too.

ъ
							*E211*
  File "{filename}" no longer available

The file which you have started editing has disappeared, or is no longer
accessible.  Make sure you write the buffer somewhere to avoid losing
changes.  This message is not given when 'buftype' is not empty.


С уважением,Виктор./+7920 6899105

 
 

Sent: Monday, April 08, 2019 at 3:42 AM

**Comment by amix** [comment]
Thanks for answering, folks 🙏 I'm closing this down.
