### ISSUE TITLE
How to change python max line?

### ISSUE THREAD

**Issue by ardinusawan** [amix/vimrc#524]
Hi, how can I set the max line when I code using python?
The default is 120 and I want to set it to 99 chars.

In `~/.vim_runtime/my_configs.vim` already add `let g:flake8_max_line_length=99` with no luck.
Maybe because this command was already deprecated?

I try my luck using `max-line-length = 99`, but ale give my error `E492: Not an editor command: max-line-length = 99`.

**Comment by pollackscience** [comment]
I use a flake8 config file located at `~/.config/flake8` with the following lines:

```shell
[flake8]
ignore = E221,E226,F403,F401,E402
max-line-length = 100
```

See http://flake8.pycqa.org/en/latest/user/configuration.html for more details.

**Comment by ardinusawan** [comment]
@pollackscience We supposed to put that in `~/.vim_runtime/my_configs.vim` right? Not in `~/.config/flake8`

I do that but give me error `E492: Not an editor command: max-line-length = 99.`

**Comment by pollackscience** [comment]
Your issue might be due to a confusion between Ale (https://github.com/w0rp/ale) and Syntastic (https://github.com/vim-syntastic/syntastic).  Looks like amix recently switched to Ale from Syntastic, so check to make sure you're configuring the correct plugin.  Either way, I think specifying in `~/.config/flake8` should work fine if you're comfortable with doing so... I don't think anyone will arrest you for using a flake8 config instead of a vim plugin config.

**Comment by ardinusawan** [comment]
@pollackscience I don't see `~/.config/flake8` folder/file. Should I create it manually?

**Comment by pollackscience** [comment]
Sorry for the late reply, yes, you can just create it manually.

**Comment by amix** [comment]
Thanks for taking care of this @pollackscience 🙏
