### ISSUE TITLE
No highlighting or underline for spell check after awesome vimrc install

### ISSUE THREAD

**Issue by majamin** [amix/vimrc#548]
I have a fresh install of Ubuntu Desktop (18.04), installed awesome vimrc as per instructions and everything works as expected, except when I spell check using `<leader>ss`, then moving through unrecognized words using `<leader>sn` or `]s`.

It moves to misspelled words, but no highlighting or underlining of words appears on screen. Is this the expected behaviour? If so, is there a way to turn it this back on?

Also, this is my first "issue" submission, so if this is not the venue for these types of queries, please let me know.

**Comment by amix** [comment]
This isn't something I can reproduce, @majamin. You can try to run it in another environment or try with another color scheme.

**Comment by bryango** [comment]
I see the same problem. A related issue is https://github.com/amix/vimrc/issues/418. It seems to be a problem of the default color scheme `peaksea.vim`

https://github.com/amix/vimrc/blob/5108ca4ec066ed9b93bab2c7f5b0d37d244ac0a9/sources_forked/peaksea/colors/peaksea.vim#L206-L220

https://github.com/amix/vimrc/blob/5108ca4ec066ed9b93bab2c7f5b0d37d244ac0a9/sources_forked/peaksea/colors/peaksea.vim#L540-L554

The reason is listed in the changelog of peaksea, v3.3: https://www.vim.org/scripts/script.php?script_id=760

> Anton Sharnov thinks it is better to leave the foreground color as is for spell error in 256-color cterm. If you agree this, the version 3.3 is for you, else you can just edit the source.

I have since created a fork to re-enable the colors. See if it helps!
